# -*- coding: utf-8 -*-
"""2. Vowel or consonant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyYjoTMF38qcdhDbuewER3vbhBP35ofS
"""

letter=input("Enter a single character:")
if len(letter) !=1 or not letter.isalpha():
  print("please enter a valid single letter.")
elif letter in "aeiou":
    print(f"{letter} is a vowel.")
else:
    print(f"{letter} is a consonant.")