# -*- coding: utf-8 -*-
"""3.Temperature converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3toy-ZOqq8IVGWVvEj1AjHqkVeNzW6k
"""

temp=float(input("Enter temperature:"))
choice=input("convert to (F)arenheit or (C)elsius?")
if choice == "f":
  converted = (temp*9/5)+32
  print(f"{temp} Celsius is {converted} Farenheit.")
elif choice == "c":
  converted = (temp-32) * 5/9
  print(f"{temp} Farenheit is {converted} Celsius.")
else:
  print("Invalid choice.")