# -*- coding: utf-8 -*-
"""Largest number finder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQknZFt6to4hccyLraKAz_wzBzqRlw-H
"""

num1 = float(input("Enter first number:"))
num2 = float(input("Enter second number:"))
num3 = float(input("Enter third number:"))
largest = max(num1 , num2 , num3)
print(f"The largest number is {largest}.")