# -*- coding: utf-8 -*-
"""simple calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCsXHKgDo8gf2EfD6EE6dvxqzHljsmTd
"""

a=int(input())
b=int(input())
add=a+b
print(add)
substract=a-b
print(substract)
multiply=a*b
print(multiply)
devide=a/b
print(devide)